# Generated by Django 6.0.7 on 2026-08-08 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_demoevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.RemoveField(
            model_name='tasktemplate',
            name='project_type',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='ProjectType',
        ),
        migrations.DeleteModel(
            name='TaskTemplate',
        ),
    ]
