# Generated by Django 6.0.7 on 2026-08-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_create_cache_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannerrule",
            name="project_types",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
