# Generated by Django 6.0.7 on 2026-08-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_backfill_planner_rule_project_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeekCloseout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iso_year", models.PositiveIntegerField()),
                ("iso_week", models.PositiveSmallIntegerField()),
                ("completed_count", models.PositiveIntegerField(default=0)),
                ("rescheduled_count", models.PositiveIntegerField(default=0)),
                ("added_count", models.PositiveIntegerField(default=0)),
                ("summary_text", models.TextField(blank=True)),
                ("closed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-iso_year", "-iso_week"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("iso_year", "iso_week"), name="unique_iso_week_closeout"
                    )
                ],
            },
        ),
    ]
