# Generated by Django 6.0.7 on 2026-09-03 15:17

from django.db import migrations, models


def mark_seeded_if_rules_already_exist(apps, schema_editor):
    """Backward compatibility for any environment that already ran the old,
    row-count-based seed_rules before this migration existed — e.g. a
    maintainer who invoked it by hand before entrypoint.sh called it
    automatically. Without this, the next seed_rules run would find no
    RulesSeeded marker and duplicate the INITIAL_RULES on top of what is
    already there. A fresh environment has no PlannerRule rows yet at this
    point in its migration history, so this is a no-op for it."""
    PlannerRule = apps.get_model("projects", "PlannerRule")
    RulesSeeded = apps.get_model("projects", "RulesSeeded")
    if PlannerRule.objects.exists():
        RulesSeeded.objects.create()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_weekcloseout"),
    ]

    operations = [
        migrations.CreateModel(
            name="RulesSeeded",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seeded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(mark_seeded_if_rules_already_exist, noop),
    ]
