"""
Django settings for planning_hub project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# No fallback: unlike DEBUG or ALLOWED_HOSTS (#47), there is no value here
# that is both valid and safe to default to — any hardcoded string is public
# the moment it ships in this repo. Missing it must fail closed, not run
# signing and CSRF protection on a known key.
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY environment variable is not set. Set it in the "
        "environment or .env file before starting the server."
    )

DEBUG = os.environ.get("DEBUG", "false").lower() == "true"

DEMO_MODE = os.environ.get("DEMO_MODE", "false").lower() == "true"

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost 127.0.0.1").split()

CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS", "").split()

# Which process this is. Used by the HTTPS block below and by STORAGES further
# down, both of which have to behave differently under the test runner than in
# a server process.
_TESTING = sys.argv[1:2] == ["test"]

# #157: the four settings `manage.py check --deploy` asks for — secure cookies
# (W012, W016), HSTS (W004) and the HTTPS redirect (W008).
#
# Gating them on plain `not DEBUG` would break the production deployment.
# nginx.conf listens on port 80 only: there is no TLS on the Mac Mini and
# access is over VPN, so a browser would discard a `Secure`-flagged cookie and
# take sessions and every CSRF-protected POST with it. Hence a switch of its
# own, defaulting the safe way round: a fresh checkout with DEBUG=false gets
# the whole set, and the one deployment that cannot have it opts out in its own
# .env with HTTPS_ONLY=false. `check --deploy` keeps warning there, which is
# simply the truth about that deployment.
#
# DEBUG wins either way — this is an opt-*out* for a TLS-less deployment, never
# an opt-in that could make a local runserver hand out Secure cookies.
HTTPS_ONLY = not DEBUG and os.environ.get("HTTPS_ONLY", "true").lower() == "true"

SESSION_COOKIE_SECURE = HTTPS_ONLY
CSRF_COOKIE_SECURE = HTTPS_ONLY

# One hour, deliberately short. A browser remembers HSTS for the whole max-age
# and refuses plain HTTP for the domain until it expires, so a mistake here
# cannot be taken back by fixing the server — only waited out. Raise it to a
# year once HTTPS has been confirmed clean on every host that serves this
# domain; an hour is the value that stays recoverable while that is still
# being established.
#
# SECURE_HSTS_INCLUDE_SUBDOMAINS stays off (Django's default): ligaauguste.de
# carries more than this app, and those are not this deployment's to promise
# for. See SILENCED_SYSTEM_CHECKS below for the two checks that asks for.
SECURE_HSTS_SECONDS = 3600 if HTTPS_ONLY else 0

# nginx terminates TLS, so Django only ever sees an HTTP request and would
# never emit the HSTS header without being told. Trusting a client-settable
# header is only safe because the demo's nginx overwrites it rather than
# passing it through (`proxy_set_header X-Forwarded-Proto https`,
# nginx-demo.conf) — the two are pinned together in HttpsOnlySettingsConfTest.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https") if HTTPS_ONLY else None

# nginx owns the real redirect (its 80 block sends everything to 443); this is
# the fallback that makes W008 true rather than merely handled elsewhere.
#
# `not _TESTING` is not optional: the test client speaks http://, and CI runs
# without a .env so DEBUG defaults to false — every request in the suite would
# answer 301 before reaching a view.
SECURE_SSL_REDIRECT = HTTPS_ONLY and not _TESTING

# Turning HSTS on raises two new warnings, so silencing them is what keeps
# this from trading four warnings for two:
#
#   W005 — wants SECURE_HSTS_INCLUDE_SUBDOMAINS. Declined above: the other
#          subdomains of this domain are not this app's to commit.
#   W021 — wants the HSTS preload flag, which requires includeSubDomains plus
#          a max-age of at least a year, and submits the domain to a list
#          browsers ship. Both are the opposite of the cautious start above.
SILENCED_SYSTEM_CHECKS = ["security.W005", "security.W021"]


# Application definition

INSTALLED_APPS = [
    "projects",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "planning_hub.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "planning_hub.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DEMO_MODE:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "data" / "demo.sqlite3",
            # #255 follow-up: this one file holds the demo's sessions and its
            # DatabaseCache, and since gunicorn serves it from eight threads
            # rather than two processes (entrypoint.sh), eight requests can
            # want to write to it at once. SQLite admits one writer at a time
            # whichever way the concurrency was bought, so without these three
            # the added capacity is a reading one and the extra writers queue
            # on defaults that were never chosen.
            #
            # WAL lets readers through while a write is in flight, which is
            # most of this traffic — a dashboard render reads the cache and
            # the session and writes neither. The journal mode is a property
            # of the file, so the PRAGMA is a no-op after the first
            # connection; it is issued on every one because Django offers no
            # once-per-database hook.
            #
            # IMMEDIATE takes the write lock when the transaction opens
            # instead of upgrading to it halfway through: an upgrade that
            # finds the lock held fails at once and does not wait out `timeout`
            # at all, which is the "database is locked" most applications
            # actually meet. `timeout` is the wait itself, raised from
            # sqlite3's own five seconds — a request here can be sitting in a
            # Claude call, and queueing a few seconds longer is a better
            # answer than a 500.
            #
            # Production is PostgreSQL and needs none of it.
            "OPTIONS": {
                "init_command": "PRAGMA journal_mode=WAL;",
                "transaction_mode": "IMMEDIATE",
                "timeout": 20,
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "planning_hub"),
            "USER": os.environ.get("DB_USER", "liga"),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "de"

TIME_ZONE = "Europe/Berlin"

# No LOCALE_PATHS, no {% trans %} anywhere — the app's own strings are
# hardcoded German. This stays on purely so Django translates its own
# admin chrome (login form, model list) via its bundled de translations.
USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Hashed static filenames (#74): collectstatic renames every file
# {% static %} references to name.<contenthash>.ext and records the mapping
# in a manifest, so a changed file is a new URL and no browser cache can pin
# a stale copy — the pre-#64 bootstrap.min.css survived its own replacement
# in visitors' caches exactly that way. Hashing only applies with
# DEBUG = False; runserver keeps plain names.
#
# The test runner forces DEBUG = False but never runs collectstatic, so the
# suite would trip over the missing manifest — it keeps the plain storage,
# the arrangement the Django docs recommend for testing under
# ManifestStaticFilesStorage.
#
# Overriding STORAGES replaces Django's whole default dict, so the "default"
# file storage has to be restated even though it just repeats the default.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if _TESTING
            else "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"
        ),
    },
}

# Structured logging for the Claude API calls (#31): duration, tokens and
# outcome per call, since the Anthropic console can't attribute a call to a
# view and the dashboard's 8h cache hides a slow or expensive call otherwise.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "plain": {"format": "{asctime} {levelname} {name} {message}", "style": "{"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "plain"},
    },
    "loggers": {
        "projects": {
            "handlers": ["console"],
            "level": "CRITICAL" if _TESTING else "INFO",
            "propagate": False,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "planning_hub_cache",
    }
}
